### ISSUE TITLE
data loss on keyboard interrupt

### ISSUE THREAD

**Issue by jusschwitalla** [QUARK-framework/QUARK#111]
Hi together,

if I run a QUARK configuration with many repetitions and I interrupt the QUARK run with CTRL-C the results of the iterations already done get lost. 

This is because  the json.dump which comes after the repetitions loop is not done in this case. One solution could be to do this json.dump also in the "except KeyboardInterrupt" section. 

best wishes,
Jürgen

**Comment by philross** [comment]
Hi Jürgen, 

thank you for the issue, we will fix it in #112.

**Comment by jusschwitalla** [comment]
Hi Philipp,

great – thank’s for the quick reaction.

Von: Philipp ***@***.***>
Gesendet: Donnerstag, 22. Februar 2024 10:43
An: QUARK-framework/QUARK ***@***.***>
Cc: jusschwitalla ***@***.***>; Author ***@***.***>
Betreff: Re: [QUARK-framework/QUARK] data loss on keyboard interrupt (Issue #111)


Hi Jürgen,

thank you for the issue, we will fix it in #112<https://github.com/QUARK-framework/QUARK/pull/112>.

**Comment by Marvmann** [comment]
Fixed with PR #112.
Note: On Windows machines, there is an issue with CTRL-C not being handled as Keyboard Interrupt when importing certain packages (see [this thread](https://stackoverflow.com/questions/42653389/ctrl-c-causes-forrtl-error-200-rather-than-python-keyboardinterrupt-exception)), which are part of the full requirements of QUARK at the moment. The fix in PR #112 might, therefore, not work on Windows, which will be addressed in a future fix if necessary.
